Support prerequisite transactions in dynamic tables write
ytsaurus/ytsaurus pull request #162
Opened 2023-11-15 15:38 UTC by gritukan

We are building a service that uses dynamic tables as a metadata storage. Cypress is used for a leader election and prerequisite transactions are used to prevent races, however prerequisite transactions are not supported for dynamic table operations. This PR fixes that.

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

2023-11-15 19:20 UTC, zlobober commented on yt/yt/server/master/cell_server/tamed_cell_manager.cpp
> +        auto leaseTransactionIds = cell->LeaseTransactionIds();
const auto&?

2023-11-22 11:28 UTC, savrus requested changes

2023-11-22 11:28 UTC, savrus commented on yt/yt/server/node/tablet_node/tablet_cell_write_manager.cpp
> +                }
Копипаста с кодом выше. Может сделаем хелпер?

2023-11-22 11:28 UTC, savrus commented on yt/yt/ytlib/api/native/client_internal_impl.cpp
> +    WaitFor(cellDirectorySynchronizer->Sync())
Давай сделаем хелпер GetSyncCellChannelOrThrow, чтобы запускать синк, только если cell directory ещё не знает про целл

2023-11-22 11:28 UTC, savrus commented on yt/yt/tests/integration/dynamic_tables/test_dynamic_tables_leases.py
> +    def _restart_cell(self):
Есть такая штука: https://github.com/ytsaurus/ytsaurus/blob/4c3689e0117cfb69397144e473d393b420dd264d/yt/yt/tests/library/yt_dynamic_tables_base.py#L34

2023-11-29 14:45 UTC, gritukan commented on yt/yt/server/lib/lease_server/lease_manager.cpp
> +        MaybeRemoveLease(lease);
Good observation!

2023-11-29 14:59 UTC, savrus commented
Shipped!

2023-11-29 15:49 UTC, savrus commented
Shipped!

2023-12-05 04:52 UTC, closed without merging