Issue #191: Set container cpu limit in CRI job environement
ytsaurus/ytsaurus pull request #192
Opened 2023-11-27 15:59 UTC by koct9i

2023-11-27 16:40 UTC, koct9i commented on yt/yt/server/node/exec_node/job.cpp
> +        if (*proxyConfig->ContainerCpuLimit < 0) {
I've implemented the same logic as job-proxy has for porto job-environment:

https://github.com/ytsaurus/ytsaurus/blob/c6039f5f41cfe1eb2467ce8fbe12e3654e88f491/yt/yt/server/job_proxy/job_proxy.cpp#L820

2023-11-28 17:10 UTC, gritukan requested changes

2023-11-28 17:10 UTC, gritukan commented on yt/yt/server/lib/job_proxy/config.cpp
> +    registrar.Parameter("container_cpu_limit", &TThis::ContainerCpuLimit);
Shouldn't we add `.Default()` here?

2023-11-28 17:10 UTC, gritukan commented on yt/yt/server/node/exec_node/job.cpp
> +        if (*proxyConfig->ContainerCpuLimit < 0) {
I'm pretty sure that the negation of > 0 here is == 0, not < 0

2023-11-28 17:19 UTC, koct9i commented on yt/yt/server/node/exec_node/job.cpp
> +        if (*proxyConfig->ContainerCpuLimit < 0) {
my bad, should be ( <= 0)

2023-12-04 16:55 UTC, yalekseev commented
Shipped!

2023-12-04 19:43 UTC, closed without merging