Add option to adjust job OOM score
ytsaurus/ytsaurus pull request #363
Opened 2024-01-31 17:13 UTC by koct9i

2024-02-01 11:32 UTC, gritukan commented on yt/yt/server/node/exec_node/job.cpp
> +    return MaxOOMScore - (MaxOOMScore * reservedMemory + totalMemory - 1) / totalMemory;
Can't this TODO be easily fixed by taking UserJobs limit from memory usage tracker?

2024-02-07 09:19 UTC, k-pogorelov requested changes

2024-02-07 09:19 UTC, k-pogorelov commented on yt/yt/server/node/exec_node/job.cpp
> +    return MaxOOMScore - (MaxOOMScore * reservedMemory + totalMemory - 1) / totalMemory;
I'm not sure it is a suitable formula.
Why does MaxOOMScore decrease from an increase in memory demand?

2024-02-12 12:57 UTC, koct9i commented on yt/yt/server/node/exec_node/job.cpp
> +    auto totalMemory = Bootstrap_->GetMemoryUsageTracker()->GetTotalLimit();
I don't think so. Thist must be common cgroup memory limit for all jobs.
Thiere is no such thing yet.

And more likely this should be part of NodeResouceManager.

2024-02-15 12:03 UTC, k-pogorelov commented on yt/yt/server/node/exec_node/job.cpp
> +    auto totalMemory = Bootstrap_->GetMemoryUsageTracker()->GetTotalLimit();
Yes, this must be common cgroup memory limit for all jobs. And this limit must be returned by JobResourceManager->GetResourceLimits().

2024-07-22 16:13 UTC, koct9i commented
Later

2024-07-22 16:13 UTC, closed without merging