configurable primary_medium for odin_checks and dynamic_table_commands check tables
ytsaurus/ytsaurus pull request #476
Opened 2024-03-20 05:34 UTC by kruftik

2024-03-26 07:32 UTC, Kontakter commented on yt/odin/checks/bin/dynamic_table_commands/__main__.py
> +        logger.info('Created temp directory %s (primary_medium=%s)', temp_path, temp_table_primary_medium)
`'.... (primary_medium: %s)'`

2024-04-01 08:48 UTC, kruftik commented
@Kontakter , pls take another look

2024-04-02 09:05 UTC, Kontakter approved these changes
Looks good!

2024-04-02 09:53 UTC, Kontakter requested changes
This PR brokes some tests:

```
yt/odin/tests/test_db.py:83: in test_yt_db_for_cluster
    init_yt_table(TABLE, client, bundle="default")
E   TypeError: init_yt_table() missing 1 required positional argument: 'primary_medium'
```

2024-04-02 10:31 UTC, kruftik commented
> This PR brokes some tests:
> 
> ```
> yt/odin/tests/test_db.py:83: in test_yt_db_for_cluster
>     init_yt_table(TABLE, client, bundle="default")
> E   TypeError: init_yt_table() missing 1 required positional argument: 'primary_medium'
> ```

just fixed it

2024-04-02 11:45 UTC, Kontakter commented
Shipped!

2024-04-02 13:39 UTC, Kontakter requested changes
```
yt/odin/tests/test_db.py:72: in test_yt_db
    init_yt_table(TABLE, client, bundle="default")
E   TypeError: init_yt_table() missing 1 required positional argument: 'primary_medium'
```

Do you run all tests and check all usages?

2024-04-04 07:26 UTC, kruftik commented
@Kontakter 

> ```
> yt/odin/tests/test_db.py:72: in test_yt_db
>     init_yt_table(TABLE, client, bundle="default")
> E   TypeError: init_yt_table() missing 1 required positional argument: 'primary_medium'
> ```
> 
> Do you run all tests and check all usages?

to be honest, not really :( but for now, I seem to have fixed all the mentions.

could you try again?

2024-04-04 07:58 UTC, Kontakter commented
Shipped!

2024-04-04 11:09 UTC, closed without merging