Add network name to spyt with yt scheduler
ytsaurus/ytsaurus pull request #519
Opened 2024-04-09 13:35 UTC by mamogaaa

2024-04-12 07:32 UTC, alextokarew requested changes

2024-04-12 07:32 UTC, alextokarew commented on yt/spark/spark-over-yt/project/Dependencies.scala
> +  lazy val ytsaurusClientVersion = "1.2.1-SNAPSHOT"
Как временная мера подойдёт, но перед мержем в мастер здесь нужно будет указать релизную версию

2024-04-12 07:32 UTC, alextokarew commented on yt/spark/spark-over-yt/resource-manager/src/main/scala/org/apache/spark/deploy/ytsaurus/YTsaurusClusterApplication.scala
> +    var ytProxy = conf.get("spark.hadoop.yt.clientProxy", null)
`var ytProxy = conf.get("spark.hadoop.yt.clientProxy", YTsaurusUtils.parseMasterUrl(masterURL))`
и соответственно if ниже тоже не нужен

2024-04-12 07:32 UTC, alextokarew commented on yt/spark/spark-over-yt/resource-manager/src/main/scala/org/apache/spark/deploy/ytsaurus/YTsaurusClusterApplication.scala
> +    var ytProxy = conf.get("spark.hadoop.yt.clientProxy", null)
Хотя вообще непонятен смысл заведения тут дополнительного параметра, почему бы сразу не передавать нужный адрес в `--master ytsaurus://...`?

2024-04-16 10:08 UTC, mamogaaa commented on yt/spark/spark-over-yt/resource-manager/src/main/scala/org/apache/spark/deploy/ytsaurus/YTsaurusClusterApplication.scala
> +    var ytProxy = conf.get("spark.hadoop.yt.clientProxy", null)
пофиксил

2024-04-16 10:09 UTC, mamogaaa commented on yt/spark/spark-over-yt/resource-manager/src/main/scala/org/apache/spark/deploy/ytsaurus/YTsaurusClusterApplication.scala
> +    var ytProxy = conf.get("spark.hadoop.yt.clientProxy", null)
Внутри и снаружи облака отличаются хостнеймы. Плохо представляю как решить эту проблему иначе(

2024-04-18 07:55 UTC, alextokarew requested changes

2024-04-18 07:55 UTC, alextokarew commented on yt/spark/spark-over-yt/resource-manager/src/main/scala/org/apache/spark/scheduler/cluster/ytsaurus/YTsaurusOperationManager.scala
> +  def create(ytProxy: String, conf: SparkConf, networkName: String): YTsaurusOperationManager = {
Здесь, и ниже в `buildClient`, параметр `networkName` можно указать как `networkName: Option[String]`. Тогда в классах выше можно избавиться от `null`-ов.

2024-04-18 07:55 UTC, alextokarew commented on yt/spark/spark-over-yt/resource-manager/src/main/scala/org/apache/spark/deploy/ytsaurus/YTsaurusClusterApplication.scala
> +    val networkName = conf.get("spark.hadoop.yt.clientProxyNetworkName", null)
Тут можно убрать null, изменив тип `networkName` на Option[String]

2024-04-18 17:13 UTC, closed without merging