add option for ignore system py modules while pickling
ytsaurus/ytsaurus pull request #562
Opened 2024-04-30 15:27 UTC by dmi-feo

2024-04-30 15:42 UTC, Kontakter commented
I have an embarrassing question: could you add a test for the new options?

2024-05-02 09:35 UTC, gritukan commented on yt/python/yt/wrapper/py_wrapper.py
> +            # regular module
nip: Typically we start comments from capital letter and end with the dot

2024-05-02 09:35 UTC, gritukan commented on yt/python/yt/wrapper/py_wrapper.py
> +        def path_is_for_system_module(_path):
is_system_module_path?

2024-05-06 17:16 UTC, Kontakter approved these changes

2024-05-06 20:00 UTC, Kontakter commented
There are some cosmetic errors:
```
yt/python/yt/wrapper/tests/test_operations.py:1525: [F401] 'fakemodule' imported but unused
yt/python/yt/wrapper/tests/test_operations.py:1550: [E303] too many blank lines (2)
```

2024-05-06 20:01 UTC, Kontakter requested changes
See comment above

2024-05-06 21:53 UTC, Kontakter commented
Also there is a following error while running tests with system python:
```
...
yt/wrapper/py_wrapper.py", line 297, in create_modules_archive_default
    for pattern in get_config(client)["pickling"]["system_module_patterns"]
TypeError: 'NoneType' object is not iterable
```

2024-05-08 09:07 UTC, dmi-feo commented
> Also there is a following error while running tests with system python:
> 
> ```
> ...
> yt/wrapper/py_wrapper.py", line 297, in create_modules_archive_default
>     for pattern in get_config(client)["pickling"]["system_module_patterns"]
> TypeError: 'NoneType' object is not iterable
> ```

@Kontakter  Could you tell me more about the environment you launched the test in? I didn't manage to reproduce the error. Does `test_create_modules_archive` pass in that case?

2024-05-10 10:14 UTC, Kontakter approved these changes
To run tests

2024-05-11 16:46 UTC, closed without merging