Add enum.StrEnum and enum.IntEnum support for yt_dataclasses
ytsaurus/ytsaurus pull request #585
Opened 2024-05-16 12:00 UTC by thenno

related to https://github.com/ytsaurus/ytsaurus/issues/195

2024-05-17 11:46 UTC, thenno commented on yt/python/yt/wrapper/schema/types.py
> -    check_schema_module_available()
Maybe I've recklessly deleted this code, but it looks like it doesn't depend on python's version and skiff_bindings.

2024-05-27 13:52 UTC, denvr requested changes
Changes Requested

2024-05-29 12:53 UTC, thenno commented on yt/python/yt/wrapper/schema/types.py
> -    check_schema_module_available()
Yes, it's common behavior, but that looks kinda strange.

I expected `check_schema_module_available` check in the top-level functions/objects, who really need skiff to work.

But I agree with you, it's not a good idea to change this only in one function.

2024-05-29 12:53 UTC, thenno commented on yt/python/yt/wrapper/schema/types.py
> +def yt_enum(ti_type, to_yt_type=None, from_yt_type=None):
In my opinion, we shouldn't try to guess the type at runtime by content.
If we guess the type the user may get unpleasant effects, for example:

```
import enum

class C(enum.IntEnum):
    a = 1

# will be mapped to Int8

# after some time user can add another value

class C(enum.IntEnum):
    a = 1
    b = 214748364700

# now it maps to UInt64 implicitly
```

On the one hand we can try to guess the type by base type, but on the other hand we have to set the most general data type (for example Int64 for int), and this provokes suboptimal user behavior (nobody like to override defaults:) ).

2024-05-29 12:53 UTC, thenno commented on yt/python/yt/wrapper/schema/types.py
> +    return _wrapper
https://docs.python.org/3/library/typing.html#typing.Annotated -> typing._AnnotatedAlias

But the approach to the solution has been changed, please see the last comment.

2024-05-29 12:53 UTC, thenno commented on yt/python/yt/wrapper/tests/typed_api/test_typed_api.py
> +        class CustomStrEnum(enum.StrEnum):
StrEnums was added in python3.11 -> so it should work.

Could you please clarify why you're asking this question? Opensource/closedsource ya make uses python 3.12.3, this file already contains new futures from 3.10 (new Union syntax). I can't see any potential problems here.

2024-05-29 12:54 UTC, thenno commented on yt/python/yt/wrapper/tests/typed_api/test_typed_api.py
> +            D = 4
It's a very good point.

I've checked only my usual use of enums, but annotated enum doesn't support all enum's magic.

For example, it damage iteration by enum-class: https://github.com/python/typing/discussions/1440
There is the same problem with dict-like access to the class. The worst thing is that it depends on the python version.

Thus my bold idea doesn't really work -> I propose to separate the annotation of the type and its actual use.

2024-06-06 16:34 UTC, denvr requested changes
Small notes in the tests, type hints

2024-06-06 16:34 UTC, denvr commented on yt/python/yt/wrapper/schema/types.py
> +def create_yt_enum(py_type, ti_type, to_yt_type=None, from_yt_type=None):
Type annotations will make work easier (it not so easy to understand what `ti_type` is)

2024-06-06 16:34 UTC, denvr commented on yt/python/yt/wrapper/tests/typed_api/test_typed_api.py
> +        class CustomStrEnum(enum.StrEnum):
My bad. I mean "below python 3.11". The closedsource `ya make` uses python 3.12, but the code should still support python 3.8+.
It turns out the tests were ahead of the code.

2024-06-06 16:34 UTC, denvr commented on yt/python/yt/wrapper/schema/types.py
> +def yt_enum(ti_type, to_yt_type=None, from_yt_type=None):
Of course defaults assumes wider types. As wide as regular integer field, without specific type annonations.

2024-06-17 00:09 UTC, denvr commented
Shipped!

2024-06-20 09:05 UTC, closed without merging