Add connect timeout
ytsaurus/ytsaurus pull request #640
Opened 2024-06-04 21:13 UTC by kaikash

2024-07-16 21:00 UTC, maxim-babenko requested changes

2024-07-16 21:00 UTC, maxim-babenko commented on yt/yt/core/net/dialer.cpp
> +            const auto deadline = Min(
Typically we don't use const for locals

2024-07-16 21:00 UTC, maxim-babenko commented on yt/yt/core/net/dialer.cpp
> +                Deadline_ ? *Deadline_ : TInstant::Max(),
Let's use value_or

2024-07-16 21:00 UTC, maxim-babenko commented on yt/yt/core/net/dialer.cpp
> +                << TErrorAttribute("Timeout", Config_->ConnectTimeout);
Timeout -> timeout (attributes are in lower case)

2024-07-16 21:00 UTC, maxim-babenko commented on yt/yt/core/net/dialer.cpp
> +                << TErrorAttribute("Timeout", Config_->ConnectTimeout);
"Connect timed out" above vs "Connect timeout" below -- let's choose a single spelling

2024-07-22 09:57 UTC, maxim-babenko commented
Shipped!

2024-07-22 10:18 UTC, maxim-babenko requested changes

2024-07-22 10:18 UTC, maxim-babenko commented on yt/yt/core/net/config.cpp
> +    registrar.Parameter("connect_timeout", &TThis::ConnectTimeout);
Please add ``Default()`` here

2024-07-26 04:31 UTC, Kontakter approved these changes
To run internal tests

2024-07-31 18:50 UTC, kaikash commented on yt/yt/core/net/config.cpp
> +        .Default();
The reason I haven't set any timeout here is that doing so would change the current behavior of internal clusters and could potentially cause some problems.

2024-08-01 10:37 UTC, gritukan commented on yt/yt/core/net/config.cpp
> +        .Default();
I see. Honestly I do not see any way how reasonable timeout can break something here, but let's wait for code maintainers.

2024-08-01 10:45 UTC, maxim-babenko commented
Shipped!

2024-08-01 10:45 UTC, maxim-babenko commented on yt/yt/core/net/config.cpp
> +        .Default();
15 secs seems a reasonable limit, let's try this revision

2024-08-01 10:46 UTC, gritukan commented on yt/yt/core/net/config.cpp
> +        .Default();
Discussed with @maxim-babenko, 15 seconds should be reasonable in all cases.

2024-08-05 18:01 UTC, kaikash commented on yt/yt/core/net/config.h
> +    std::optional<TDuration> ConnectTimeout;
Makes sense. Also, renamed `Timeout_` to `ReconnectTimeout_` for a better readability.

2024-08-07 13:49 UTC, gritukan commented on yt/yt/core/net/dialer.cpp
> +        YT_LOG_DEBUG("Connect timeout; trying to reconnect (Reconnect timeout: %v)",
ReconnectTimeout

2024-08-07 21:35 UTC, maxim-babenko commented
Shipped!

2024-08-08 06:29 UTC, closed without merging