Async slot initialization
ytsaurus/ytsaurus pull request #643
Opened 2024-06-05 20:58 UTC by abogutskiy

Resolves #588

2024-06-05 21:45 UTC, gritukan commented
Please capitalize the commit message

2024-06-05 21:54 UTC, gritukan commented on yt/yt/server/node/exec_node/job_environment.cpp
> +static constexpr auto AsyncInitTimeout = TDuration::Minutes(10); // TODO(abogutskiy) add as config parametr
Yeah, it should be moved to config

2024-06-05 21:54 UTC, gritukan commented on yt/yt/server/node/exec_node/job_environment.cpp
> +            return DoInit(slotCount, cpuLimit,idleCpuFraction)
space after ,

2024-06-05 21:54 UTC, gritukan commented on yt/yt/server/node/exec_node/job_environment.cpp
> +        auto slotInitFuture = BIND([this, slotIndex] {
this can be simplified with `BIND(&IJobEnvironment::CleanProcesses, MakeStrong(this), slotIndex)`

2024-06-05 21:54 UTC, gritukan commented on yt/yt/server/node/exec_node/job_environment.cpp
> +        slotInitFuture.Subscribe(BIND([this](const TErrorOr<void>& result){
We use `[this, this_ = MakeStrong(this)]` to keep object alive until callback execution

2024-06-05 21:54 UTC, gritukan commented on yt/yt/server/node/exec_node/job_environment.cpp
> +        slotInitFuture.Subscribe(BIND([this](const TErrorOr<void>& result){
`TErrorOr<void>` is just a `TError`

2024-06-05 21:54 UTC, gritukan commented on yt/yt/server/node/exec_node/job_environment.cpp
> +        slotInitFuture.Subscribe(BIND([this](const TErrorOr<void>& result){
We usually call such a variable error not a result

2024-06-05 21:54 UTC, gritukan commented on yt/yt/server/node/exec_node/job_environment.cpp
> +            if (!result.IsOK()) {
I'd prefer to handle an error in slot manager where this computation is started.

2024-06-05 21:54 UTC, gritukan commented on yt/yt/server/node/exec_node/job_environment.cpp
> +        return slotInitFuture.AsVoid();
Isn't it already TFuture<void>?

2024-06-05 21:54 UTC, gritukan commented on yt/yt/server/node/exec_node/job_environment.cpp
> +        return MakeFuture(TErrorOr<void>());
just `return VoidFuture`

2024-06-05 21:54 UTC, gritukan commented on yt/yt/server/node/exec_node/job_environment.cpp
> +        return MakeFuture(TErrorOr<void>()); // no async init needed
Here also `VoidFuture`

2024-06-05 21:54 UTC, gritukan commented on yt/yt/server/node/exec_node/job_environment.cpp
> +        auto slotInitFuture = BIND([this, slotIndex] {
`this_ = MakeStrong(this)`

2024-06-05 21:54 UTC, gritukan commented on yt/yt/server/node/exec_node/job_environment.cpp
> +                for (auto slotType: {ESlotType::Common, ESlotType::Idle}) {
Extra identation here

2024-06-05 21:54 UTC, gritukan commented on yt/yt/server/node/exec_node/job_environment.cpp
> +        slotInitFuture.Subscribe(BIND([this](const TErrorOr<void>& result){
Here are the same issues as with the similar construction above

2024-06-05 21:54 UTC, gritukan commented on yt/yt/server/node/exec_node/job_environment.cpp
> +        WaitFor(Executor_->RunPodSandbox(New<NCri::TCriPodSpec>())).ThrowOnError();
`ThrowOnError` should be on the next line

2024-06-05 21:54 UTC, gritukan commented on yt/yt/server/node/exec_node/job_environment.cpp
> +        // init fake slot to download resource once before running init slots concurrently
Comments start with the capital letter and end with the dot as regular sentences

2024-06-05 21:54 UTC, gritukan commented on yt/yt/server/node/exec_node/job_environment.cpp
> +        WaitFor(Executor_->RunPodSandbox(New<NCri::TCriPodSpec>())).ThrowOnError();
Waiting here can be avoided by chaining futures with Apply

2024-06-05 21:54 UTC, gritukan commented on yt/yt/server/node/exec_node/job_environment.cpp
> +    TActionQueuePtr MounterThread_ = New<TActionQueue>("CriMounter");
Why is it mutable?

2024-06-05 21:54 UTC, gritukan commented on yt/yt/server/node/exec_node/slot_manager.h
> +    TRWMutex FreeSlotsMutex_;
We use TReaderWriterSpinLock instead of mutexes

2024-06-06 10:24 UTC, gritukan commented on yt/yt/server/node/exec_node/job_environment.cpp
> +                WaitFor(PortoExecutor_->CreateContainer(slotContainer))
These futures also can be chained but let's leave it as is for now

2024-06-06 10:24 UTC, gritukan commented on yt/yt/server/node/exec_node/job_environment.cpp
> +            for (auto slotType: {ESlotType::Common, ESlotType::Idle}) {
space before :

2024-06-06 10:25 UTC, gritukan commented on yt/yt/server/node/exec_node/job_environment.cpp
> +        slotInitFuture.Subscribe(BIND([this, this_ = MakeStrong(this), slotIndex](const TErrorOr<TCriPodDescriptor>& result){
space between [] and ()

2024-06-06 10:25 UTC, gritukan commented on yt/yt/server/node/exec_node/job_environment.cpp
> +            if (result.IsOK()) {  // Error is handled outside in slot manager
Let's move the comment on a line above

2024-06-06 10:26 UTC, gritukan commented on yt/yt/server/node/exec_node/job_environment.h
> +void Disable(const TError& error);
What is it?

2024-06-06 10:26 UTC, gritukan commented on yt/yt/server/node/exec_node/slot_manager.cpp
> +        slotInitFuture.Subscribe(BIND([this, this_ = MakeStrong(this), slotIndex](const TError& error) {
space between [] and ()

2024-06-06 10:27 UTC, gritukan commented on yt/yt/server/node/exec_node/slot_manager.cpp
> +                Disable(error);
Let's wrap an error:
```
auto wrappedError = TError("Failed to initialize slot %v", slotIndex) << error
```

2024-06-06 20:30 UTC, gritukan approved these changes
LGTM

2024-06-06 20:30 UTC, gritukan commented on yt/yt/server/node/exec_node/job_environment.cpp
> +     void DoInit(int slotCount, double cpuLimit, double idleCpuFraction) override
Extra spaces?

2024-06-11 14:30 UTC, k-pogorelov requested changes

2024-06-11 14:30 UTC, k-pogorelov commented on yt/yt/server/node/exec_node/slot_manager.cpp
> +                JobEnvironment_->Disable(wrappedError);
std::move()

2024-06-11 15:17 UTC, k-pogorelov requested changes

2024-06-11 15:17 UTC, k-pogorelov commented on yt/yt/server/node/exec_node/slot_manager.cpp
> +                JobEnvironment_->Disable(wrappedError);
Resurrection has been working here in case of Porto job environment.
Now we may lose slot forever. Let's add retries here

2024-06-20 11:43 UTC, k-pogorelov requested changes

2024-06-20 11:43 UTC, k-pogorelov commented on yt/yt/server/node/exec_node/slot_manager.h
> +    TRingQueue<int> FreeSlots_;  // For usage in main thread only, use bootstrap job invoker to run via
We write comments at previous line.
If you want to write explicit, comment, you can just write
// Invoker affinity: JobInvoker

2024-06-20 11:43 UTC, k-pogorelov commented on yt/yt/tests/integration/node/test_user_job.py
> +            command='cat > /dev/null; python -c \'print("head" + "0" * 10000000); print("1" * 10000000 + "tail")\' >&2;',
It was not fixed :(

2024-06-25 13:52 UTC, k-pogorelov approved these changes

2024-06-25 14:05 UTC, k-pogorelov approved these changes

2024-06-25 14:16 UTC, DimasKovas approved these changes

2024-07-01 10:23 UTC, k-pogorelov commented
test_user_job.py::TestHealExecNode::test_force_reset_persistent_alert (ignat) is crashing

2024-07-05 11:36 UTC, abogutskiy commented
> test_user_job.py::TestHealExecNode::test_force_reset_persistent_alert (ignat) is crashing

I have tried to run this test without porto and it finished without any errors. Can you give me the trace for the crash, please?

2024-07-12 04:59 UTC, gritukan commented on yt/yt/server/node/exec_node/slot_manager.cpp
> +                    FreeSlots_.clear();
Why do you do it here? This is not the only place where job env can be disabled. I'd suggest to clean free slots just before this loop.

2024-07-12 11:40 UTC, k-pogorelov approved these changes

2024-07-12 13:09 UTC, k-pogorelov approved these changes

2024-07-12 16:16 UTC, k-pogorelov approved these changes

2024-07-16 09:32 UTC, closed without merging