support custom dill params
ytsaurus/ytsaurus pull request #670
Opened 2024-06-19 19:25 UTC by dmi-feo

For the sake of https://github.com/ytsaurus/ytsaurus/issues/663

Why `NO_CHOICE` has been introduced:
Since we have some logic for the params (we redefine them for interactive environments), we need to distinguish the situation where the user did not set any value ( == made no choice) with the situation where they actually did (and user's choice should be used no matter what). `None` is a bad option since one day it might become a meaningful value for the params. And `dill_kwargs` cannot be empty by default - `VerifiedDict` has a very strict check for keys when setting (there are a few exceptions in `keys_to_ignore`, but it looks like a crutch, so I guess we don't want to add new keys). Similar approach is used in aiohttp (https://github.com/aio-libs/aiohttp/blob/fc32f69e16f221133d8ee01d2e9928fde35ff02a/aiohttp/client.py#L437), they use enum for such values, but it doesn't seem to make much difference.

2024-06-20 12:03 UTC, Kontakter commented
We already have such a class: https://github.com/ytsaurus/ytsaurus/blob/main/yt/python/yt/wrapper/cypress_commands.py#L25

I offer to generalize it and use it here, by generalize I mean move it in common.py

2024-06-20 15:45 UTC, dmi-feo commented
Thank you! I updated the PR

2024-06-21 09:45 UTC, Kontakter approved these changes

2024-06-21 10:21 UTC, dmi-feo commented on yt/python/yt/wrapper/tests/test_operations_pickling.py
> +        rows = [dynamic_dataclass(str='a')]
fixed

2024-06-21 10:22 UTC, dmi-feo commented on yt/python/yt/wrapper/default_config.py
> +import enum
Not needed, it was there in early versions, now it is removed

2024-06-21 11:33 UTC, Kontakter approved these changes

2024-06-24 08:41 UTC, Kontakter commented
This test is broken, let figure out how to fix it

https://github.com/ytsaurus/ytsaurus/blob/f2ddadc0ad28116e44988d7f5701558d9beb6089/yt/python/yt/wrapper/tests/test_misc.py#L1365

2024-06-24 08:42 UTC, Kontakter requested changes
See comment above

2024-06-24 12:45 UTC, Kontakter approved these changes

2024-07-18 07:55 UTC, closed without merging