Detect job OOM
ytsaurus/ytsaurus pull request #681
Opened 2024-06-24 14:07 UTC by koct9i

- Detect when any process was killed by OOM killer in user job environment
  Always report here abort reason resource overdraft regardless of
  exit status of job main process - correct handing is not expected.
  
- Detect when job proxy is killed by OOM killer
  Report that abort reason is resource overdraft.
  
- Add option memory_oom_group for killing all tasks at OOM

2024-07-16 10:40 UTC, Kontakter commented
@k-pogorelov is reading this PR, comments will be published soon

2024-07-16 10:49 UTC, k-pogorelov requested changes

2024-07-26 04:31 UTC, Kontakter commented
For transparency: k-pogorelov is on vacation till 4th August. If we need to accept this PR sooner – tell us.

2024-08-05 14:34 UTC, k-pogorelov approved these changes

2024-08-05 16:04 UTC, k-pogorelov approved these changes

2024-08-06 12:31 UTC, closed without merging