Add documentation for Jupyter Notebooks in YT
ytsaurus/ytsaurus pull request #727
Opened 2024-07-23 12:32 UTC by gritukan

2024-07-24 13:36 UTC, ogorbacheva requested changes

2024-07-24 13:36 UTC, ogorbacheva commented on yt/docs/ru/_includes/user-guide/jupyt.md
> +Содержимое ноутбуков и файлы, созданные на файловой системе теряются при перезапуске джоба с ноутбуком. Для надёжного хранения файлов необходимо использовать Кипарис.
Пропущена запятая после слова "системе":
 _Содержимое ноутбуков и файлы, созданные на файловой системе, теряются..._

2024-07-24 13:36 UTC, ogorbacheva commented on yt/docs/ru/_includes/user-guide/jupyt.md
> +Содержимое ноутбуков и файлы, созданные на файловой системе теряются при перезапуске джоба с ноутбуком. Для надёжного хранения файлов необходимо использовать Кипарис.
Предлагаю тут добавить ссылку на Кипарис: 
`Для надёжного хранения файлов необходимо использовать [Кипарис](../user-guide/storage/cypress.md).`

2024-07-24 13:36 UTC, ogorbacheva commented on yt/docs/ru/toc.yaml
> +      - name: Jupyter notebooks
Давайте в меню раздел назовём так же, как и саму статью:
"Jupyter notebooks" -> "Работа с Jupyter Notebooks"

2024-07-24 13:36 UTC, ogorbacheva commented on yt/docs/ru/_includes/user-guide/jupyt.md
> +Для развёртывания ноутбука необходимо выполнить следующие действия.
Лучше в конце предложения поставить `:`, так как ниже идёт перечисление действий.

2024-07-24 13:36 UTC, ogorbacheva commented on yt/docs/en/_includes/user-guide/jupyt.md
> +Following actions are required to launch a notebook.
Here, let's use `:` instead of the period?

2024-07-24 13:36 UTC, ogorbacheva commented on yt/docs/en/_includes/user-guide/jupyt.md
> +1. Select docker-image of the jupyter-notebook. You can use [jupyter stacks](https://jupyter-docker-stacks.readthedocs.io/en/latest/) as a image or as a base of the image. Example of such an image is
as a image -> as an image

2024-07-24 13:36 UTC, ogorbacheva commented on yt/docs/en/_includes/user-guide/jupyt.md
> +Notebooks and files created on filesystem are not preserved after job restart. For the reliable storage of the files you should store them in Cypress.
Let's add link to the Cypress article:
`For the reliable storage of the files you should store them in [Cypress](../user-guide/storage/cypress.md).`

2024-07-25 12:17 UTC, Kontakter approved these changes

2024-07-25 20:06 UTC, closed without merging