Small code improvements for TShellManager
ytsaurus/ytsaurus pull request #743
Opened 2024-07-27 15:44 UTC by abogutskiy

Fix cosmetic issues for https://github.com/ytsaurus/ytsaurus/pull/719

2024-07-27 16:41 UTC, gritukan approved these changes

2024-07-28 05:05 UTC, maxim-babenko commented
Shipped!

2024-07-30 14:28 UTC, maxim-babenko requested changes

2024-07-30 14:28 UTC, maxim-babenko commented on yt/yt/server/lib/shell/shell_manager.cpp
> +            if (auto shell = Find(*shellIndex); shell) {
``; shell`` is redundant (here and below)

2024-07-30 14:28 UTC, maxim-babenko commented on yt/yt/server/lib/shell/shell_manager.cpp
> +            if (auto shell = Find(*shellIndex); shell) {
Also this is a wrong find:)

2024-08-01 10:36 UTC, maxim-babenko commented
Shipped!

2024-08-05 19:13 UTC, closed without merging