Add yt bus handshake proto for golang
ytsaurus/ytsaurus pull request #890
Opened 2024-10-16 12:32 UTC by koct9i

2024-10-22 14:57 UTC, verytable commented
Shipped!

2024-10-22 15:09 UTC, verytable commented
Shipped!

2024-10-22 15:53 UTC, verytable commented
Shipped

2024-10-22 15:53 UTC, verytable commented
Shipped!

2024-10-22 17:22 UTC, verytable commented
Internal tests failed on this change. Working on exporting subset of failed tests.

2024-11-12 19:07 UTC, verytable commented
We've exported some of the failing tests https://github.com/ytsaurus/ytsaurus/commit/841fd449938bd0f0d19b898e2123bdddbe0516ab#diff-9f2e52f52f5a131a746f248a61976d5001cae9e262532c73dfcc3e900c24bb13

You can try to manually reproduce problems using sample rpc service https://github.com/ytsaurus/ytsaurus/blob/main/yt/yt/core/rpc/unittests/bin/main.cpp

2024-11-22 10:09 UTC, Kontakter requested changes
See comments by @verytable

2025-01-14 17:41 UTC, koct9i commented
Ok, let's look into this again.

I cannot reproduce any issues using this test against past and current main branch.
Maybe I'm doing something wrong.

```
khlebnikov@dev0:~/src/ytsaurus$ export TEST_SERVICE_BINARY_PATH=$PWD/yt/yt/core/rpc/unittests/bin/bin
khlebnikov@dev0:~/src/ytsaurus$ ./ya make -A yt/go/bus/ 
------- [TS] {debug, default-linux-x86_64} yt/go/bus/gotest/gotest >> gotest::TestTestService/Compression [GOOD]
Test command err:
2025-01-14 18:35:17,665228	I	RpcServer	RPC service registered (ServiceName: TestService, RealmId: 0-0-0-0, BusServerId: 557352e6-96e819c7-d79a684f-cec6ff3b)	bin		
2025-01-14 18:35:17,667450	I	RpcServer	RPC server started (BusServerId: 557352e6-96e819c7-d79a684f-cec6ff3b)	bin		
2025-01-14 18:35:17,693499	W	Main	Server major protocol version differs from client major protocol version: 0 != 1\n    code            101\n    origin          (unknown) (pid 1021196, thread BusXferFS:2, fid fffeed595811b0a0)\n    datetime        2025-01-14T17:35:17.693431Z\n    method          SlowCall\n    realm_id        0-0-0-0\n    endpoint        tcp://[::1]:45022\n    request_id      91575b18-300faeb9-f74aa2a1-72cbe8eb\n    service         TestService\n	BusXferFS:2	fffeed595811b0a0	
2025-01-14 18:35:18,271809	I	RpcServer	RPC service registered (ServiceName: TestService, RealmId: 0-0-0-0, BusServerId: 7342ee15-4bea1b2f-cc28c81e-6b218678)	bin		
2025-01-14 18:35:18,273721	I	RpcServer	RPC server started (BusServerId: 7342ee15-4bea1b2f-cc28c81e-6b218678)	bin		
2025-01-14 18:35:18,303781	W	Main	Unknown method\n    code            103\n    origin          (unknown) (pid 1021244, thread BusXferFS:1, fid fffeed5957ec8c62)\n    datetime        2025-01-14T17:35:18.303713Z\n    method          NonExistingMethod\n    realm_id        0-0-0-0\n    endpoint        tcp://[::1]:45136\n    request_id      396f516e-96281396-77480866-7a4cfd75\n    service         TestService\n	BusXferFS:1	fffeed5957ec8c62	
2025-01-14 18:35:20,890441	I	RpcServer	RPC service registered (ServiceName: TestService, RealmId: 0-0-0-0, BusServerId: c7c11d43-ce76b0e3-5e9e2d03-4e9b58be)	bin		
2025-01-14 18:35:20,892366	I	RpcServer	RPC server started (BusServerId: c7c11d43-ce76b0e3-5e9e2d03-4e9b58be)	bin		
2025-01-14 18:35:20,999675	I	RpcServer	RPC service registered (ServiceName: TestService, RealmId: 0-0-0-0, BusServerId: 44837b7d-87d05a6-440baf1b-5b1d0a95)	bin		
2025-01-14 18:35:21,001536	I	RpcServer	RPC server started (BusServerId: 44837b7d-87d05a6-440baf1b-5b1d0a95)	bin		
2025-01-14 18:35:21,174594	I	RpcServer	RPC service registered (ServiceName: TestService, RealmId: 0-0-0-0, BusServerId: 86a2f035-e975cd92-5575b05e-f95f6c1d)	bin		
2025-01-14 18:35:21,176781	I	RpcServer	RPC server started (BusServerId: 86a2f035-e975cd92-5575b05e-f95f6c1d)	bin

Total 4 suites:
	4 - GOOD
Total 44 tests:
	44 - GOOD
Ok
```

2025-01-15 09:57 UTC, koct9i commented
@Kontakter @verytable Let's try import this PR again and see which test exactly is borken.
Probably last time that was more than just one commmit.
I could start fresh PR if it makes it easier.

2025-01-15 10:03 UTC, Kontakter commented
Shipped!

2025-01-15 10:04 UTC, Kontakter commented
Ok, let's try to do it

2025-01-16 10:23 UTC, Kontakter commented
Some tests fail, but it seems to be flaps.

@verytable – could you take a closer look?

2025-01-16 10:25 UTC, koct9i commented
Please how me something. At least names.

2025-01-16 10:34 UTC, Kontakter commented
> Please how me something. At least names.

It is some internal test

2025-01-17 13:28 UTC, closed without merging