Add per-band options for rpc bus connection parallelism
ytsaurus/ytsaurus pull request #895
Opened 2024-10-17 14:38 UTC by koct9i

- Set requst multiplexing parallelism in chunk client
  
- Add for RPC bus band config options for range of multiplexing parallelism

2024-10-18 11:36 UTC, maxim-babenko commented
Shipped!

2024-10-18 11:36 UTC, maxim-babenko commented
Let's run some tests just in case

2024-10-24 12:47 UTC, maxim-babenko requested changes

2024-10-24 12:47 UTC, maxim-babenko commented on yt/yt/core/bus/tcp/config.cpp
> +            "min_multiplexing_parallelism exceeds max_multiplexing_parallelism");
Let's place option names in double quotes

2024-10-24 12:47 UTC, maxim-babenko commented on yt/yt/core/bus/public.h
> +constexpr int DefaultMaxMultiplexingParallelism = 1000;
1'000

2024-10-24 12:47 UTC, maxim-babenko commented on yt/yt/core/rpc/channel.h
> +    // Parallelism is adjusted by per-brand configuration.
per-band

2024-11-04 10:06 UTC, Kontakter approved these changes
To rerun tests in internal CI

2024-11-04 19:14 UTC, closed without merging