yt/go/sdk: refactor YT_PROXY cluster URL handling
ytsaurus/ytsaurus pull request #898
Opened 2024-10-18 16:07 UTC by koct9i

* handle https scheme in YT_PROXY
* fix several HTTPS/TVM/... cases
* add unit test with same test cases as python SDK

2024-10-18 16:20 UTC, koct9i commented
For the record: YT-20028

2024-10-21 19:43 UTC, tinarsky requested changes

2024-10-21 19:43 UTC, tinarsky commented on yt/go/yt/config_test.go
> +			"short_host_w_schame",
schame -> scheme

2024-10-21 19:43 UTC, tinarsky commented on yt/go/yt/config_test.go
> +func TestClusterUrl(t *testing.T) {
Url -> URL

2024-10-21 19:43 UTC, tinarsky commented on yt/go/yt/config_test.go
> +		t.Logf("checking %q", test.name)
I propose using t.Run instead of printing the test name.

2024-10-22 10:08 UTC, tinarsky approved these changes
LGTM

2024-10-22 16:55 UTC, closed without merging