Fix grafana func serializers
ytsaurus/ytsaurus pull request #941
Opened 2024-11-11 22:22 UTC by jasminetealover

In grafana there can be collapsable group of panels. Let's add it in here by extending `Rowset` class. Also fixed some typos for grafana. And added ability to have `sum` without label (which can be handy when we want to sum all the series)

2024-11-12 02:25 UTC, jasminetealover commented on yt/admin/dashboards/yt_dashboards/common/postprocessors.py
> +            value = value.replace(ContainerTemplate, "{{pod}}")
`ContainerTemplate -> {{pod}}` is very YT specific replacement, makes sense to have it in yt postprocessor

2024-11-14 23:52 UTC, Kontakter commented
This comment is not for this specific PR, but it seems that we need to add unit tests for the grafana and monitoring serializers

2024-11-18 08:22 UTC, Kontakter requested changes

2024-11-27 17:48 UTC, jasminetealover commented on yt/admin/dashboard_generator/yt_dashboard_generator/specific_sensors/monitoring.py
> +            return ", ".join(serialized_elements)
good catch!

2024-11-27 17:50 UTC, jasminetealover commented
> This comment is not for this specific PR, but it seems that we need to add unit tests for the grafana and monitoring serializers

Yes. This would be very convenient. It's currently almost impossible to test monitoring generators.

2024-11-28 09:26 UTC, Kontakter approved these changes

2024-11-28 17:05 UTC, closed without merging